package scaffold

import "fmt"

func projectFiles(o Options) map[string]string {
	files := map[string]string{
		"go.mod":                         fmt.Sprintf("module %s\n\ngo 1.26.5\n", o.Module),
		".gitignore":                     ".env\nbin/\n*.db\n*.db-shm\n*.db-wal\n",
		".env.example":                   "PORT=8080\n",
		"internal/models/.gitkeep":       "",
		"internal/services/.gitkeep":     "",
		"internal/repositories/.gitkeep": "",
		"migrations/.gitkeep":            "",
		"internal/config/config.go": `package config
import "os"
type Config struct { Port string; DatabaseDSN string }
func Load() Config {
 port := os.Getenv("PORT")
 if port == "" { port = "8080" }
 return Config{Port: port, DatabaseDSN: os.Getenv("DATABASE_DSN")}
}
`,
	}
	routerImport, router, health := "", "", ""
	switch o.Framework {
	case "std":
		router = `r := http.NewServeMux()
r.HandleFunc("GET /health", handlers.Health)`
		health = `package handlers
import "net/http"
func Health(w http.ResponseWriter, r *http.Request) {
 w.Header().Set("Content-Type", "application/json")
 w.Write([]byte("{\"status\":\"ok\"}\n"))
}`
	case "gin":
		routerImport = `"github.com/gin-gonic/gin"`
		router = `r := gin.Default()
r.GET("/health", handlers.Health)`
		health = `package handlers
import ("net/http"; "github.com/gin-gonic/gin")
func Health(c *gin.Context) { c.JSON(http.StatusOK, gin.H{"status":"ok"}) }`
	case "echo":
		routerImport = `"github.com/labstack/echo/v5"`
		router = `r := echo.New()
r.GET("/health", handlers.Health)`
		health = `package handlers
import ("net/http"; "github.com/labstack/echo/v5")
func Health(c *echo.Context) error { return c.JSON(http.StatusOK, map[string]string{"status":"ok"}) }`
	}
	files["internal/handlers/health.go"] = health
	files["internal/server/router.go"] = fmt.Sprintf(`package server
import (
 "net/http"
 %s
 "%s/internal/handlers"
)
func Router() http.Handler {
 %s
 return r
}
`, routerImport, o.Module, router)
	dbImport, dbSetup := "", ""
	if o.Database != "none" {
		dbImport = fmt.Sprintf("%q", o.Module+"/internal/database")
		dbSetup = `db, err := database.Open(cfg.DatabaseDSN)
 if err != nil { log.Fatal(err) }
 defer db.Close()`
		files["internal/database/database.go"] = databaseSource(o)
		dsn := map[string]string{
			"postgres": "postgres://postgres:postgres@localhost:5432/" + o.Name + "?sslmode=disable",
			"mysql":    "root:password@tcp(localhost:3306)/" + o.Name + "?charset=utf8mb4&parseTime=true&loc=Local",
			"sqlite":   "app.db",
		}[o.Database]
		files[".env.example"] += "DATABASE_DSN=" + dsn + "\n"
	}
	files["cmd/server/main.go"] = fmt.Sprintf(`package main
import (
 "errors"
 "log"
 "net/http"
 "time"
 "%s/internal/config"
 "%s/internal/server"
 %s
)
func main() {
 cfg := config.Load()
 %s
 srv := &http.Server{Addr: ":"+cfg.Port, Handler: server.Router(), ReadHeaderTimeout: 5*time.Second}
 log.Printf("listening on %%s", srv.Addr)
 if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) { log.Fatal(err) }
}
`, o.Module, o.Module, dbImport, dbSetup)
	files["README.md"] = fmt.Sprintf(`# %s

Generated by GoWeld. Framework: %s. Database: %s. Data access: %s.

Requires Go 1.26.5 or newer. Install dependencies once with `+"`go mod tidy`"+`.
This resolves external dependencies and writes their versions to go.mod and go.sum; commit both files.

Configuration is read from the process environment. .env files are not loaded automatically.
To use the example in a POSIX shell:

`+"```sh"+`
cp .env.example .env
set -a
. ./.env
set +a
goweld run
`+"```"+`

For PostgreSQL/MySQL, start your database and create the database first, then set DATABASE_DSN.
SQLite with GORM requires CGO and a C compiler; SQLite with sql uses the pure-Go modernc driver.
The server checks the configured connection on startup. Health: GET /health.

Commands (from this project root):

`+"```sh"+`
goweld generate model User
goweld generate handler User
goweld generate service User
goweld build
`+"```"+`

Generators create starter files; implement business logic and register handlers in internal/server/router.go.
Handlers return HTTP 501 until implemented. Database Open returns a closable connection wrapper:
use its DB field for queries. Pass this dependency to your services/repositories as needed.
No migrations run automatically; migrations/ is reserved for your migration files.

Layout:
- cmd/server: application entry point
- internal/config: environment configuration
- internal/server and internal/handlers: routing and HTTP handlers
- internal/models, internal/services, internal/repositories: application layers
- internal/database: database connection (when selected)
- migrations: database migrations
`, o.Name, o.Framework, o.Database, o.ORM)
	return files
}

func databaseSource(o Options) string {
	if o.ORM == "gorm" {
		driver := o.Database
		return fmt.Sprintf(`package database
import (
 "context"
 "fmt"
 "time"
 "gorm.io/gorm"
 "gorm.io/driver/%s"
)
type Connection struct { DB *gorm.DB }
func Open(dsn string) (*Connection, error) {
 if dsn == "" { return nil, fmt.Errorf("DATABASE_DSN is required") }
 db, err := gorm.Open(%s.Open(dsn), &gorm.Config{DisableAutomaticPing: true})
 if err != nil { return nil, err }
 raw, err := db.DB()
 if err != nil { return nil, err }
 ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
 defer cancel()
 if err := raw.PingContext(ctx); err != nil { raw.Close(); return nil, err }
 return &Connection{DB: db}, nil
}
func (c *Connection) Close() error {
 db, err := c.DB.DB()
 if err != nil { return err }
 return db.Close()
}
`, driver, driver)
	}
	driver := map[string]string{"postgres": "pgx", "mysql": "mysql", "sqlite": "sqlite"}[o.Database]
	pkg := map[string]string{"postgres": "github.com/jackc/pgx/v5/stdlib", "mysql": "github.com/go-sql-driver/mysql", "sqlite": "modernc.org/sqlite"}[o.Database]
	return fmt.Sprintf(`package database
import (
 "context"
 "database/sql"
 "fmt"
 "time"
 _ %q
)
type Connection struct { DB *sql.DB }
func Open(dsn string) (*Connection, error) {
 if dsn == "" { return nil, fmt.Errorf("DATABASE_DSN is required") }
 db, err := sql.Open(%q, dsn)
 if err != nil { return nil, err }
 ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
 defer cancel()
 if err := db.PingContext(ctx); err != nil { db.Close(); return nil, err }
 return &Connection{DB: db}, nil
}
func (c *Connection) Close() error { return c.DB.Close() }
`, pkg, driver)
}
